### ISSUE TITLE
Saving with auto export destructively removes empty nodes from scene

### ISSUE THREAD

**Issue by DylanRJohnston** [kaosat-dev/Blender_bevy_components_workflow#149]
When saving with the auto export plugin, empty nodes are destructively removed from the scene (cannot be recovered with undo) and the script produces the following error.

```
Traceback (most recent call last):
  File "/Users/dylanj/Library/Application Support/Blender/4.0/scripts/addons/gltf_auto_export/auto_export/auto_export.py", line 116, in auto_export
    export_main_scene(bpy.data.scenes[scene_name], folder_path, addon_prefs, library_collections)
  File "/Users/dylanj/Library/Application Support/Blender/4.0/scripts/addons/gltf_auto_export/auto_export/export_main_scenes.py", line 57, in export_main_scene
    generate_and_export(
  File "/Users/dylanj/Library/Application Support/Blender/4.0/scripts/addons/gltf_auto_export/helpers/generate_and_export.py", line 57, in generate_and_export
    bpy.ops.object.mode_set( mode = original_mode )
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() Context missing active object
```

I've been trying to used empty nodes to mark spawn point and camera positions, but they get destroyed upon save. Turning them into blueprints works but it a bit of extra work.

**Comment by DylanRJohnston** [comment]
For now I've created a generic "Marker" blueprint which I then customize with the required components once it's instanced in the scene. This ensures there's only a single extraneous `glb` file created.

Actually upon second thought, I could probably just override the behavior so it doesn't get split out into its own file.

**Comment by kaosat-dev** [comment]
Do you mean Blender's "Empty" Objects ? 
Those should be exported normally, have been using them for testing for a while, even added an automated test, and they  are exported as they should, cannot reproduce this issue.
As in the other issue you reported, I would need more information to reproduce & fix
* are you using them in your main or library scene ?
* what is your setup (ie more information about scene etc)
* what version of ```gltf_auto_export``` are you using ?

**Comment by DylanRJohnston** [comment]
I'm happy to share it publicly as it's already on github https://github.com/DylanRJohnston/deep-space-derby/blob/main/simulation/game.blend

**Comment by kaosat-dev** [comment]
@DylanRJohnston Thanks for the file !
I was actually able to reproduce this issue ! 
* It turns out , the issue is with empties inside another collection, inside the main scene :D  I'll try to fix that asap.
* Btw I was not able to reproduce the error with change detection, even with your example file .
* I do not know if you are interested in feedback as far as project organization (Blender side) goes, but I would have a few tips if you want ? (some things I noticed while trying out your blend file)

**Comment by kaosat-dev** [comment]
@DylanRJohnston , sadly I spoke too soon: while I was able to reproduce this issue with your blend file, the tests I added for this, and any other project I tested this with have not had this issue :(
I tried various levels of nesting of empties, inside & outside collections etc

**Comment by DylanRJohnston** [comment]
Yeah definitely, I’m super new to blender and largely have no idea what I’m doing.
